package com.zhongyan.uav.task.executor;

import com.zhongyan.uav.asset.domain.Asset;
import com.zhongyan.uav.asset.domain.AssetRepository;
import com.zhongyan.uav.asset.domain.AssetRole;
import com.zhongyan.uav.asset.domain.AssetType;
import com.zhongyan.uav.asset.domain.TaskAsset;
import com.zhongyan.uav.asset.domain.TaskAssetRepository;
import com.zhongyan.uav.asset.port.AssetObject;
import com.zhongyan.uav.asset.port.AssetStoragePort;
import com.zhongyan.uav.asset.port.StoredObject;
import com.zhongyan.uav.task.domain.Task;
import com.zhongyan.uav.task.domain.TaskType;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Clock;
import java.time.Instant;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

public class ReportGenerationTaskExecutor extends AbstractMetadataTaskExecutor {
    private final AssetStoragePort assetStoragePort;

    public ReportGenerationTaskExecutor(AssetRepository assetRepository, TaskAssetRepository taskAssetRepository,
                                        AssetStoragePort assetStoragePort) {
        this(assetRepository, taskAssetRepository, assetStoragePort, Clock.systemUTC());
    }

    public ReportGenerationTaskExecutor(AssetRepository assetRepository, TaskAssetRepository taskAssetRepository,
                                        AssetStoragePort assetStoragePort, Clock clock) {
        super(assetRepository, taskAssetRepository, clock);
        this.assetStoragePort = assetStoragePort;
    }

    @Override
    public boolean supports(TaskType taskType) {
        return taskType == TaskType.REPORT_GENERATION;
    }

    @Override
    public TaskExecutionResult execute(TaskExecutionContext context) {
        Task task = context.task();
        String markdown = reportMarkdown(task);
        byte[] content = markdown.getBytes(StandardCharsets.UTF_8);
        String objectKey = "reports/" + task.taskId() + "/report.md";
        String checksum = "sha256:" + sha256(content);
        Map<String, Object> metadata = new LinkedHashMap<>(metadata(task, "report-generation"));
        metadata.put("mock", false);
        metadata.put("storage", "object-storage");
        metadata.put("format", "markdown");
        metadata.put("checksum", checksum);
        StoredObject stored = assetStoragePort.put(new AssetObject(objectKey, new ByteArrayInputStream(content),
                content.length, "text/markdown", Map.of(
                "taskId", task.taskId(),
                "missionId", task.missionId(),
                "assetRole", AssetRole.REPORT.name())));
        createReportAsset(task, stored, checksum, metadata);
        return success(task, "report-generation", metadata);
    }

    private Asset createReportAsset(Task task, StoredObject stored, String checksum, Map<String, Object> metadata) {
        Instant now = clock.instant();
        Asset asset = Asset.created("asset-" + UUID.randomUUID(), task.missionId(), task.taskId(),
                AssetType.REPORT, AssetRole.REPORT, task.taskId() + "-report.md", stored.objectKey(),
                stored.contentType(), stored.contentLength(), checksum, metadata, task.createdBy(), now)
                .markAvailable(now);
        Asset saved = assetRepository.save(asset);
        taskAssetRepository.save(new TaskAsset(task.taskId(), saved.assetId(), AssetRole.REPORT, now));
        return saved;
    }

    private String reportMarkdown(Task task) {
        Object configured = task.configSnapshot().get("reportMarkdown");
        if (configured == null) {
            configured = task.configSnapshot().get("draftMarkdown");
        }
        if (configured instanceof String markdown && !markdown.isBlank()) {
            return markdown;
        }
        return """
                # Mission Report

                - Mission: %s
                - Task: %s
                - Generated At: %s

                This report was generated by REPORT_GENERATION Task from confirmed task configuration.
                """.formatted(task.missionId(), task.taskId(), clock.instant());
    }

    private String sha256(byte[] content) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(digest.digest(content));
        } catch (Exception exception) {
            throw new IllegalStateException("failed to calculate report checksum", exception);
        }
    }
}
