package com.zhongyan.uav.task.domain;

public enum TaskEventType {
    CREATED,
    SUBMITTED,
    COMMAND_CREATED,
    APPROVED,
    DISPATCHED,
    STARTED,
    PROGRESS_CHANGED,
    ASSET_BOUND,
    ASSET_CREATED,
    GEO_CALCULATED,
    GEO_FAILED,
    LAYER_PENDING_APPROVAL,
    LAYER_PUBLISHED,
    COMPLETED,
    FAILED,
    RETRYING,
    CANCELLED,
    TIMEOUT
}
