ALTER TABLE agent_session
    ADD COLUMN IF NOT EXISTS user_id VARCHAR(128),
    ADD COLUMN IF NOT EXISTS title VARCHAR(255);

UPDATE agent_session
SET user_id = created_by
WHERE user_id IS NULL;

ALTER TABLE agent_session
    ALTER COLUMN user_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_session_user_updated_at
    ON agent_session (user_id, updated_at DESC);

ALTER TABLE agent_tool_call
    ADD COLUMN IF NOT EXISTS input JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS output JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS approved_by VARCHAR(128),
    ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

UPDATE agent_tool_call
SET input = arguments
WHERE input = '{}'::jsonb AND arguments IS NOT NULL;

UPDATE agent_tool_call
SET output = result
WHERE output = '{}'::jsonb AND result IS NOT NULL;

UPDATE agent_tool_call
SET approval_required = risk_level IN ('HIGH', 'CRITICAL')
WHERE approval_required = FALSE;

UPDATE agent_tool_call
SET approved_by = reviewed_by
WHERE approved_by IS NULL AND reviewed_by IS NOT NULL;

UPDATE agent_tool_call
SET approved_at = reviewed_at
WHERE approved_at IS NULL AND reviewed_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_agent_message_session
    ON agent_message (session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_tool_call_session
    ON agent_tool_call (session_id, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_tool_call_input_gin
    ON agent_tool_call USING GIN (input);

CREATE INDEX IF NOT EXISTS idx_agent_tool_call_output_gin
    ON agent_tool_call USING GIN (output);

CREATE TABLE IF NOT EXISTS agent_knowledge_document (
    document_id VARCHAR(64) PRIMARY KEY,
    source_type VARCHAR(64) NOT NULL,
    source_id VARCHAR(128),
    title VARCHAR(255),
    content TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding VECTOR(1024),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_knowledge_document_source
    ON agent_knowledge_document (source_type, source_id);

CREATE INDEX IF NOT EXISTS idx_agent_knowledge_document_created_at
    ON agent_knowledge_document (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_knowledge_document_metadata_gin
    ON agent_knowledge_document USING GIN (metadata);

CREATE INDEX IF NOT EXISTS idx_agent_knowledge_document_embedding
    ON agent_knowledge_document USING HNSW (embedding vector_cosine_ops);

COMMENT ON TABLE agent_knowledge_document IS 'Agent RAG knowledge documents with pgvector embeddings.';
COMMENT ON COLUMN agent_knowledge_document.embedding IS 'Embedding vector generated by qwen3-embedding:0.6b, dimension 1024.';
